In [1]:
import pandas as pd

In [3]:
df_train = pd.read_csv(r"/Bachelor-End-Project-Code---XAI/Archive/data\adult\adult.data")
df_train.head()

,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
0,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
1,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
2,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
3,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K
4,37,Private,284582,Masters,14,Married-civ-spouse,Exec-managerial,Wife,White,Female,0,0,40,United-States,<=50K

In [4]:
df_train.describe()

,39,77516,13,2174,0,40
count,32560.000000,3.256000e+04,32560.000000,32560.000000,32560.000000,32560.000000
mean,38.581634,1.897818e+05,10.080590,1077.615172,87.306511,40.437469
std,13.640642,1.055498e+05,2.572709,7385.402999,402.966116,12.347618
min,17.000000,1.228500e+04,1.000000,0.000000,0.000000,1.000000
25%,28.000000,1.178315e+05,9.000000,0.000000,0.000000,40.000000
50%,37.000000,1.783630e+05,10.000000,0.000000,0.000000,40.000000
75%,48.000000,2.370545e+05,12.000000,0.000000,0.000000,45.000000
max,90.000000,1.484705e+06,16.000000,99999.000000,4356.000000,99.000000

In [5]:
df_train.shape

(32560, 15)

In [6]:
df_train.keys()

Index(['39', ' State-gov', ' 77516', ' Bachelors', ' 13', ' Never-married',
       ' Adm-clerical', ' Not-in-family', ' White', ' Male', ' 2174', ' 0',
       ' 40', ' United-States', ' <=50K'],
      dtype='object')

In [7]:
df_test = pd.read_csv(r'/Bachelor-End-Project-Code---XAI/Archive/data\adult\adult.test')

In [21]:
df_test.head()

                                                                                                                        |1x3 Cross validator
25 Private   226802 11th         7  Never-married      Machine-op-inspct Own-child Black Male   0    0 40 United-States               <=50K.
38 Private   89814  HS-grad      9  Married-civ-spouse Farming-fishing   Husband   White Male   0    0 50 United-States               <=50K.
28 Local-gov 336951 Assoc-acdm   12 Married-civ-spouse Protective-serv   Husband   White Male   0    0 40 United-States                >50K.
44 Private   160323 Some-college 10 Married-civ-spouse Machine-op-inspct Husband   Black Male   7688 0 40 United-States                >50K.
18 ?         103497 Some-college 10 Never-married      ?                 Own-child White Female 0    0 30 United-States               <=50K.

In [20]:
df_test.shape

(16281, 1)

In [24]:
import pandas as pd

cols = [
    "age", "workclass", "fnlwgt", "education", "education-num",
    "marital-status", "occupation", "relationship", "race", "sex",
    "capital-gain", "capital-loss", "hours-per-week", "native-country", "income"
]

df_test = pd.read_csv(
    r"/Bachelor-End-Project-Code---XAI/Archive/data\adult\adult.test",
    names=cols,
    skiprows=1,          # skips the "|1x3 Cross validator" line
    sep=",",
    skipinitialspace=True,
    na_values="?"
)

# remove the extra dot from the labels
df_test["income"] = df_test["income"].str.replace(".", "", regex=False)

   age  workclass  fnlwgt     education  education-num      marital-status  \
0   25    Private  226802          11th              7       Never-married
1   38    Private   89814       HS-grad              9  Married-civ-spouse
2   28  Local-gov  336951    Assoc-acdm             12  Married-civ-spouse
3   44    Private  160323  Some-college             10  Married-civ-spouse
4   18        NaN  103497  Some-college             10       Never-married

          occupation relationship   race     sex  capital-gain  capital-loss  \
0  Machine-op-inspct    Own-child  Black    Male             0             0
1    Farming-fishing      Husband  White    Male             0             0
2    Protective-serv      Husband  White    Male             0             0
3  Machine-op-inspct      Husband  Black    Male          7688             0
4                NaN    Own-child  White  Female             0             0

   hours-per-week native-country income
0              40  United-States  <=50K
1              50  United-States  <=50K
2              40  United-States   >50K
3              40  United-States   >50K
4              30  United-States  <=50K
(16281, 15)

In [25]:
df_test.head()

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,income
0,25,Private,226802,11th,7,Never-married,Machine-op-inspct,Own-child,Black,Male,0,0,40,United-States,<=50K
1,38,Private,89814,HS-grad,9,Married-civ-spouse,Farming-fishing,Husband,White,Male,0,0,50,United-States,<=50K
2,28,Local-gov,336951,Assoc-acdm,12,Married-civ-spouse,Protective-serv,Husband,White,Male,0,0,40,United-States,>50K
3,44,Private,160323,Some-college,10,Married-civ-spouse,Machine-op-inspct,Husband,Black,Male,7688,0,40,United-States,>50K
4,18,NaN,103497,Some-college,10,Never-married,NaN,Own-child,White,Female,0,0,30,United-States,<=50K

In [26]:
df_test.shape

(16281, 15)

In [27]:
df_test.to_csv(r'C:\Users\irene\OneDrive\Υπολογιστής\TuE\BEP\Code\Bachelor-End-Project-Code---XAI\data\adult\adult_test')